# config/services.yaml
parameters:

services:
    _defaults:
        autowire: true      # Permite inyección automática de dependencias
        autoconfigure: true # Configura automáticamente tags de Symfony

    # Configuración para autodetección de servicios
    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/'           # Excluye el dominio (no son servicios)
            - '../src/Kernel.php'
            - '../src/Migrations/'       # Excluye migraciones si las tienes

    # Configuración explícita para interfaces e implementaciones
    App\Core\Domain\Repository\ProductRepositoryInterface:
        class: App\Core\Infrastructure\Persistence\Doctrine\DoctrineProductoRepository

    # Registro explícito del caso de uso (requerido por el error)
    App\Core\Application\UseCase\CreateProductUseCase: ~

    # Si usas otros casos de uso, regístralos igual:
    # App\Core\Application\UseCase\Product\ListProductsUseCase: ~